import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

/**
 * Architectural boundaries from CLAUDE.md, enforced by tooling rather than discipline.
 *
 *   UI  ->  Hooks  ->  Services  ->  Repositories  ->  Supabase
 *
 * Presentation code must never reach past the service layer. These zones make a
 * violation a lint failure instead of a code-review comment someone might miss.
 */
const presentationRestrictedZones = [
  {
    group: ["**/lib/supabase/*", "@/lib/supabase/*"],
    message:
      "Database access is repository-only. Fetch in a Server Component or Route Handler and pass data down as props.",
  },
  {
    group: ["**/*.repository", "**/*.repository.ts", "**/repositories/*"],
    message: "Repositories are server-only. Call a service instead.",
  },
  {
    group: ["@/lib/env", "**/lib/env"],
    message:
      "Server env is server-only and would leak secrets into the client bundle. Use @/lib/env.client for NEXT_PUBLIC_ values.",
  },
  {
    group: ["@/services/container", "**/services/container"],
    message:
      "The composition root is server-only. Resolve services in a Server Component or Route Handler.",
  },
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase gen types` — not ours to lint.
    "src/types/database.types.ts",
    // Test output: coverage reporters ship their own bundled scripts.
    "coverage/**",
    "test-results/**",
    "playwright-report/**",
  ]),

  {
    name: "peptologics/project-rules",
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      // Structured logging only. See src/lib/logger.
      "no-console": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-implicit-coercion": "error",
      "prefer-const": "error",
      "object-shorthand": ["error", "properties"],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "separate-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  {
    name: "peptologics/presentation-boundary",
    files: ["src/components/**/*.{ts,tsx}", "src/features/*/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": ["error", { patterns: presentationRestrictedZones }],
    },
  },

  {
    name: "peptologics/pure-utils",
    files: ["src/utils/**/*.ts", "src/lib/validations/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "react",
              message: "Utilities and validation schemas must stay framework-free.",
            },
            { name: "next", message: "Utilities and validation schemas must stay framework-free." },
          ],
          patterns: [
            {
              group: ["next/*", "react-dom", "@/lib/supabase/*", "@/lib/env"],
              message:
                "Utilities and validation schemas must stay framework-free and side-effect-free.",
            },
          ],
        },
      ],
    },
  },

  {
    // The logger is the one place a raw console call is correct.
    name: "peptologics/logger-exception",
    files: ["src/lib/logger/**/*.ts"],
    rules: { "no-console": "off" },
  },
]);

export default eslintConfig;
