-- Shared helpers.
--
-- No extensions are required: gen_random_uuid() has been in core Postgres since
-- 13, so pgcrypto is unnecessary. IP hashing happens in Node (see
-- src/lib/security/request.ts), so no crypto functions are needed in SQL either.

-- Stamps updated_at on UPDATE. A trigger helper, not business logic — timestamps
-- must be generated by the database so a client cannot forge them.
--
-- search_path is pinned to '' so the function cannot be hijacked by a caller
-- with a crafted search_path. pg_catalog stays implicitly searchable, so now()
-- still resolves; only objects in `public` need qualifying.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_updated_at is
  'Trigger helper: stamps updated_at on UPDATE. Not business logic.';
